namespace Portfolio.Models;

public record UiText(
    string Lang,
    string NavAria,
    string ScrollDown,
    string Phone,
    string SectionStack,
    string SectionExpertise,
    string SectionCases,
    string CaseProblem,
    string CaseSolution,
    string CaseResult,
    string SectionExperience,
    string SectionGitHub,
    string GitHubTotal,
    string GitHubLess,
    string GitHubMore,
    string GitHubOpen,
    string Culture,
    string SectionEducation,
    string SectionPrinciples,
    string SectionLanguages,
    string DigitalCertificate,
    string DegreeTitle,
    string DegreeText,
    string ContactTitle,
    string PreferredContact,
    string DownloadCv,
    string ThemeToggle)
{
    public static readonly UiText Ru = new(
        Lang: "ru",
        NavAria: "Навигация",
        ScrollDown: "Прокрутить вниз",
        Phone: "Телефон",
        SectionStack: "Стек технологий",
        SectionExpertise: "Экспертиза",
        SectionCases: "Кейсы",
        CaseProblem: "Задача",
        CaseSolution: "Решение",
        CaseResult: "Результат",
        SectionExperience: "Опыт работы",
        SectionGitHub: "GitHub",
        GitHubTotal: "Вкладов за месяц: {0}",
        GitHubLess: "меньше",
        GitHubMore: "больше",
        GitHubOpen: "Открыть профиль GitHub",
        Culture: "ru-RU",
        SectionEducation: "Образование",
        SectionPrinciples: "Как я работаю",
        SectionLanguages: "Языки",
        DigitalCertificate: "Электронный сертификат",
        DegreeTitle: "Прикладная информатика",
        DegreeText: "Высшее профильное образование + международные сертификации Cisco",
        ContactTitle: "Давайте работать вместе",
        PreferredContact: "— предпочитаемый способ связи",
        DownloadCv: "Скачать резюме",
        ThemeToggle: "Переключить светлую/тёмную тему");

    public static readonly UiText En = new(
        Lang: "en",
        NavAria: "Navigation",
        ScrollDown: "Scroll down",
        Phone: "Phone",
        SectionStack: "Tech Stack",
        SectionExpertise: "Expertise",
        SectionCases: "Case Studies",
        CaseProblem: "Problem",
        CaseSolution: "Solution",
        CaseResult: "Result",
        SectionExperience: "Experience",
        SectionGitHub: "GitHub",
        GitHubTotal: "{0} contributions in the last month",
        GitHubLess: "less",
        GitHubMore: "more",
        GitHubOpen: "Open GitHub profile",
        Culture: "en-US",
        SectionEducation: "Education",
        SectionPrinciples: "How I Work",
        SectionLanguages: "Languages",
        DigitalCertificate: "Digital certificate",
        DegreeTitle: "Applied Informatics",
        DegreeText: "Relevant university degree + international Cisco certifications",
        ContactTitle: "Let's Work Together",
        PreferredContact: "— preferred contact method",
        DownloadCv: "Download CV",
        ThemeToggle: "Toggle light/dark theme");

    public static UiText For(string lang) => lang == "en" ? En : Ru;
}
